export { Parser, parse } from "./parser.ts";
export type {
  ASTNode,
  Redirect,
  RedirectMode,
  CommandNode,
  PipelineNode,
  AndNode,
  OrNode,
  SequenceNode,
  WordNode,
  WordPart,
  TextPart,
  VariablePart,
  SubstitutionPart,
  ArithmeticPart,
  IfNode,
  ForNode,
  WhileNode,
  UntilNode,
  CaseNode,
  CaseClause,
} from "./ast.ts";
export {
  isWordNode,
  isCommandNode,
  isPipelineNode,
  isAndNode,
  isOrNode,
  isSequenceNode,
  isIfNode,
  isForNode,
  isWhileNode,
  isUntilNode,
  isCaseNode,
} from "./ast.ts";
