export { VersionControlSystem } from "./vcs.ts";
export type {
  VCSConfig,
  VCSAttributeRule,
  VCSResolvedAttributes,
  VCSDiffMode,
  VCSPatchSuppressionReason,
  Revision,
  DiffEntry,
  TreeManifest,
  TreeEntry,
  FileEntry,
  DirectoryEntry,
  VCSIndexEntry,
  VCSIndexFile,
  CommitOptions,
  CheckoutOptions,
  LogOptions,
  LogEntry,
  BranchInfo,
} from "./types.ts";
